volumes:
    postgres_data:
      name: user-service-db-volume
    keycloak_data:
      name: keycloak-data-volume

services:
  user-service-db:
    container_name: user-service-db
    image: postgres:17-alpine3.23
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    environment:
      POSTGRES_USER: ${USER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      POSTGRES_DB: userservicedb
    ports:
      - "${USER_SERVICE_DB_PORT}:5432"
    networks:
        - leilao-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d userservicedb -U ${USER_SERVICE_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.6.2
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_REPLY_TO: ${MAIL_REPLY_TO}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      KC_DB: user-service-db
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloakdb
      KC_DB_USERNAME: ${USER_SERVICE_DB_USER}
      KC_DB_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      KC_HEALTH_ENABLED: "true"
    ports:
      - "${KEYCLOAK_PORT}:8080"
    command: start-dev --import-realm
    networks:
        - leilao-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "cat /dev/null > /dev/tcp/127.0.0.1/8080 || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 15

  user-service:
    container_name: user-service
    image: shyuu7/user-service:latest
    restart: always
    ports:
      - "${USER_SERVICE_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userservicedb
      SPRING_DATASOURCE_USERNAME: ${USER_SERVICE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      KEYCLOAK_INTERNAL_URL: ${KEYCLOAK_INTERNAL_URL}
      KEYCLOAK_CLIENT_SECRET_USER_SERVICE: ${KEYCLOAK_CLIENT_SECRET_USER_SERVICE}
      S3_ENDPOINT: ${S3_ENDPOINT}
      USER_SERVICE_S3_BUCKET_NAME: ${USER_SERVICE_S3_BUCKET_NAME}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      SPRING_DATA_REDIS_HOST: ${USER_SERVICE_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${USER_SERVICE_REDIS_PORT}
      SPRING_DATA_REDIS_REPOSITORIES_ENABLED: false
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_SERVERS}
      LOGSTASH_HOST: ${LOGSTASH_HOST}
      LOGSTASH_PORT: ${LOGSTASH_PORT}
    networks:
      - leilao-network
    depends_on:
      user-service-db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      user-service-redis:
        condition: service_healthy

  user-service-redis:
    image: redis:8.8.0-alpine
    container_name: user-service-redis
    ports:
      - "${USER_SERVICE_REDIS_PORT}:6379"
    networks:
      - leilao-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  leilao-network:
    external: true