volumes:
    postgres_data:
      name: user-service-db-volume
services:
  postgres:
    container_name: user-service-postgres
    image: postgres:17-alpine3.23
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: userservicedb
    ports:
      - "5432:5432"