spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/userservicedb
    username: user
    password: userpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    default-schema: usuarios
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/userservicedb
    user: user
    password: userpass

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/leilao-service

keycloak:
  server-url: http://localhost:8081
  realm: leilao-service
  client-id: user-service-client
  client-secret: ${KEYCLOAK_CLIENT_SECRET}