spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${USER_SERVICE_DB_USER}
    password: ${USER_SERVICE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  cache:
    type: redis
  data:
    redis:
      host: ${USER_SERVICE_REDIS_HOST}
      port: ${USER_SERVICE_REDIS_PORT}
      repositories:
        enabled: false

  flyway:
    enabled: true
    default-schema: usuarios
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_INTERNAL_URL}/realms/leilao-service/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ${spring.application.name}
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: User Service do O Leiloeiro Online

keycloak:
  server-url: ${KEYCLOAK_INTERNAL_URL}
  realm: leilao-service
  client-id: user-service-client
  client-secret: ${KEYCLOAK_CLIENT_SECRET_USER_SERVICE}

s3:
  endpoint: ${S3_ENDPOINT}
  bucket-name: ${USER_SERVICE_S3_BUCKET_NAME}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}