### Sugerir Usernames baseado no nome do usuário
GET http://localhost:7000/usuarios/listar-usernames?nome=Larissa
Accept: application/json

### Listar Avatares Disponíveis no S3/MinIO
GET http://localhost:7000/usuarios/listar-pfps
Accept: application/json

### Criar Novo Usuário (Gera registro no Keycloak e no Postgres)
POST http://localhost:7000/usuarios/novo
Content-Type: application/json

{
  "nome": "Ricardo",
  "sobrenome": "Oliveira",
  "email": "ricardo_oliveira@email.com",
  "cpf": "12345678909",
  "dataNascimento": "1990-05-20",
  "telefone": "11988887777",
  "username": "ricardoouro37",
  "senha": "SenhaForte@123",
  "enderecos": [
    {
      "pais": "Brasil",
      "estado": "SP",
      "cidade": "São Paulo",
      "bairro": "Pinheiros",
      "rua": "Rua das Flores",
      "numero": "100",
      "cep": "05422-000"
    }
  ]
}

### Criar Outro Usuário (Gera registro no Keycloak e no Postgres)
POST http://localhost:7000/usuarios/novo
Content-Type: application/json

{
  "nome": "Larissa",
  "sobrenome": "Conti",
  "email": "larissaconti@email.com",
  "cpf": "14009481773",
  "dataNascimento": "1995-07-20",
  "telefone": "21987766555",
  "username": "larissaprime196",
  "senha": "SenhaForte@123",
  "enderecos": [
    {
      "pais": "Brasil",
      "estado": "SP",
      "cidade": "São Paulo",
      "bairro": "Pinheiros",
      "rua": "Rua das Flores",
      "numero": "100",
      "cep": "05422-000"
    }
  ]
}

### Obter perfil de um usuário por ID (UUID)
GET http://localhost:7000/usuarios/b2f9f754-f868-4efe-9548-ebc3c19e8f98/perfil
Accept: application/json

### Obter status de vários usuários através dos IDs (UUIDs separados por vírgula)
GET http://localhost:7000/usuarios/status?ids=501f22ce-2a94-4218-b47a-74c47b585bc6
Accept: application/json

### Consultar informações do vendedor
@ID_DO_USUARIO = b2f9f754-f868-4efe-9548-ebc3c19e8f98
GET http://localhost:7000/usuarios/{{ID_DO_USUARIO}}/seller-info
Accept: application/json

### Deletar (Inativar) Usuário
DELETE http://localhost:7000/usuarios/1f23b13f-c7b0-4a10-8366-55db05c134c2

### TESTES PARA O SCHEDULER -------------------------------------------------------------

###Verificar usuários suspensos
GET http://localhost:7000/test/scheduler/suspended
Accept: application/json

###Forçar reativação de um usuário específico
@USER_ID_SUSPENSO = f7a57d7c-2cf7-4ff1-ada3-09af30320129
POST http://localhost:7000/test/scheduler/restore/{{USER_ID_SUSPENSO}}

###Executar o scheduler manualmente
POST http://localhost:7000/test/scheduler/run

###Alterar data de suspensão para o passado
DELETE http://localhost:7000/test/scheduler/suspension-date/{{USER_ID_SUSPENSO}}

### TESTES PARA O KAFKA --------------------------------------------------------------

### Testar tópico reviews.auction.approved
POST http://localhost:7000/test/events/auction-report?userId=57aa53b2-e366-4ed4-b494-22222727a54d

### Testar tópico reviews.message.approved
POST http://localhost:7000/test/events/message-report?userId=9e63bdc5-d4e4-4a71-b31e-7557a74a3e2f

### Testar tópico transactions.status.closed
POST http://localhost:7000/test/events/payment-failed?userId=177f201f-4e1a-45a7-8261-286cb94cb3fb